name: Publish
on:
  pull_request:
    types:
      - closed
    branches:
      - next
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Bun runtime
      uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Build packages
      run: bun run build

    - name: Version and publish
      env:
        BUN_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

        if [ ${{ github.base_ref }} = main ]; then
          bun run version:release
        else
          bun run version:beta
        fi

        bun run publish:from-git
