name: Publish
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Bun runtime
      uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Build packages
      run: bun run build

    - name: Publish
      env:
        BUN_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: bun run publish:from-git
